module VerifyExamples.Accessors.SelectList.Each1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors.SelectList exposing (..)
import SelectList exposing (SelectList)
import Lens as L
import Accessors.SelectList as SL
import Accessors exposing (..)



listRecord : { foo : SelectList { bar : Int } }
listRecord =
    { foo = SelectList.fromLists [{ bar = 1 }] { bar = 2 } [{ bar = 3 }, { bar = 4 }]
    }



spec1 : Test.Test
spec1 =
    Test.test "#each: \n\n    get (L.foo << SL.each << L.bar) listRecord\n    --> SelectList.fromLists [1] 2 [3, 4]" <|
        \() ->
            Expect.equal
                (
                get (L.foo << SL.each << L.bar) listRecord
                )
                (
                SelectList.fromLists [1] 2 [3, 4]
                )