module VerifyExamples.Accessors.SelectList.Selected1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors.SelectList exposing (..)
import SelectList exposing (SelectList)
import Lens as L
import Accessors.SelectList as SL
import Accessors exposing (..)



listRecord : { foo : SelectList { bar : Int } }
listRecord =
    { foo = SelectList.fromLists [{ bar = 1 }] { bar = 2 } [{ bar = 3 }, { bar = 4 }]
    }



spec1 : Test.Test
spec1 =
    Test.test "#selected: \n\n    set (L.foo << SL.selected << L.bar) 37 listRecord\n    --> { foo = SelectList.fromLists [{ bar = 1 }] { bar = 37 } [{ bar = 3 }, { bar = 4 }] }" <|
        \() ->
            Expect.equal
                (
                set (L.foo << SL.selected << L.bar) 37 listRecord
                )
                (
                { foo = SelectList.fromLists [{ bar = 1 }] { bar = 37 } [{ bar = 3 }, { bar = 4 }] }
                )