module VerifyExamples.Accessors.SelectList.Selected2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors.SelectList exposing (..)
import SelectList exposing (SelectList)
import Lens as L
import Accessors.SelectList as SL
import Accessors exposing (..)



listRecord : { foo : SelectList { bar : Int } }
listRecord =
    { foo = SelectList.fromLists [{ bar = 1 }] { bar = 2 } [{ bar = 3 }, { bar = 4 }]
    }



spec2 : Test.Test
spec2 =
    Test.test "#selected: \n\n    get (L.foo << SL.selected << L.bar) listRecord\n    --> 2" <|
        \() ->
            Expect.equal
                (
                get (L.foo << SL.selected << L.bar) listRecord
                )
                (
                2
                )