module VerifyExamples.Accessors.At0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Lens as L
import Accessors exposing (..)



list : List { bar : String }
list = [{ bar = "Stuff" }, { bar =  "Things" }, { bar = "Woot" }]



spec0 : Test.Test
spec0 =
    Test.test "#at: \n\n    set (at 9000 << L.bar) \"Whatever\" list\n    --> list" <|
        \() ->
            Expect.equal
                (
                set (at 9000 << L.bar) "Whatever" list
                )
                (
                list
                )