module VerifyExamples.Accessors.At1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Test.Accessors.Record as R
import Accessors exposing (..)



list : List { bar : String }
list = [{ bar = "Stuff" }, { bar =  "Things" }, { bar = "Woot" }]



spec1 : Test.Test
spec1 =
    Test.test "#at: \n\n    set (at 0 << R.bar) \"Whatever\" list\n    --> [{ bar = \"Whatever\" }, { bar =  \"Things\" }, { bar = \"Woot\" }]" <|
        \() ->
            Expect.equal
                (
                set (at 0 << R.bar) "Whatever" list
                )
                (
                [{ bar = "Whatever" }, { bar =  "Things" }, { bar = "Woot" }]
                )