module VerifyExamples.Accessors.At2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Test.Accessors.Record as R
import Accessors exposing (..)



list : List { bar : String }
list = [{ bar = "Stuff" }, { bar =  "Things" }, { bar = "Woot" }]



spec2 : Test.Test
spec2 =
    Test.test "#at: \n\n    get (at 0 << R.bar) list\n    --> Just \"Stuff\"" <|
        \() ->
            Expect.equal
                (
                get (at 0 << R.bar) list
                )
                (
                Just "Stuff"
                )