module VerifyExamples.Accessors.At3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Lens as L
import Accessors exposing (..)



list : List { bar : String }
list = [{ bar = "Stuff" }, { bar =  "Things" }, { bar = "Woot" }]



spec3 : Test.Test
spec3 =
    Test.test "#at: \n\n    get (at 9000) list\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                get (at 9000) list
                )
                (
                Nothing
                )