module VerifyExamples.Accessors.EachIdx0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Lens as L
import Accessors exposing (..)



multiplyIfGTOne : (Int, { bar : Int }) -> (Int, { bar : Int })
multiplyIfGTOne ( idx, ({ bar } as rec) ) =
    if idx > 0 then
        ( idx, { bar = bar * 10 } )
    else
        (idx, rec)
listRecord : {foo : List {bar : Int}}
listRecord = { foo = [ {bar = 2}
                     , {bar = 3}
                     , {bar = 4}
                     ]
             }



spec0 : Test.Test
spec0 =
    Test.test "#eachIdx: \n\n    over (L.foo << eachIdx << snd << L.bar) ((+) 1) listRecord\n    --> {foo = [{bar = 3}, {bar = 4}, {bar = 5}]}" <|
        \() ->
            Expect.equal
                (
                over (L.foo << eachIdx << snd << L.bar) ((+) 1) listRecord
                )
                (
                {foo = [{bar = 3}, {bar = 4}, {bar = 5}]}
                )