module VerifyExamples.Accessors.Each0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Test.Accessors.Record as R
import Accessors exposing (..)



listRecord : {foo : List {bar : Int}}
listRecord = { foo = [ {bar = 2}
                     , {bar = 3}
                     , {bar = 4}
                     ]
             }



spec0 : Test.Test
spec0 =
    Test.test "#each: \n\n    over (R.foo << each << R.bar) ((+) 1) listRecord\n    --> {foo = [{bar = 3}, {bar = 4}, {bar = 5}]}" <|
        \() ->
            Expect.equal
                (
                over (R.foo << each << R.bar) ((+) 1) listRecord
                )
                (
                {foo = [{bar = 3}, {bar = 4}, {bar = 5}]}
                )