module VerifyExamples.Accessors.Each1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Test.Accessors.Record as R
import Accessors exposing (..)



listRecord : {foo : List {bar : Int}}
listRecord = { foo = [ {bar = 2}
                     , {bar = 3}
                     , {bar = 4}
                     ]
             }



spec1 : Test.Test
spec1 =
    Test.test "#each: \n\n    get (R.foo << each << R.bar) listRecord\n    --> [2, 3, 4]" <|
        \() ->
            Expect.equal
                (
                get (R.foo << each << R.bar) listRecord
                )
                (
                [2, 3, 4]
                )