module VerifyExamples.Accessors.Every0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Test.Accessors.Record as R
import Accessors exposing (..)
import Array exposing (Array)



arrayRecord : {foo : Array {bar : Int}}
arrayRecord =
    { foo =
        Array.fromList [{ bar = 2 }, { bar = 3 }, {bar = 4}]
    }



spec0 : Test.Test
spec0 =
    Test.test "#every: \n\n    over (R.foo << every << R.bar) ((+) 1) arrayRecord\n    --> {foo = Array.fromList [{bar = 3}, {bar = 4}, {bar = 5}]}" <|
        \() ->
            Expect.equal
                (
                over (R.foo << every << R.bar) ((+) 1) arrayRecord
                )
                (
                {foo = Array.fromList [{bar = 3}, {bar = 4}, {bar = 5}]}
                )