module VerifyExamples.Accessors.Every1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Test.Accessors.Record as R
import Accessors exposing (..)
import Array exposing (Array)



arrayRecord : {foo : Array {bar : Int}}
arrayRecord =
    { foo =
        Array.fromList [{ bar = 2 }, { bar = 3 }, {bar = 4}]
    }



spec1 : Test.Test
spec1 =
    Test.test "#every: \n\n    get (R.foo << every << R.bar) arrayRecord\n    --> Array.fromList [2, 3, 4]" <|
        \() ->
            Expect.equal
                (
                get (R.foo << every << R.bar) arrayRecord
                )
                (
                Array.fromList [2, 3, 4]
                )