module VerifyExamples.Accessors.Fst2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Accessors exposing (..)



charging : (String, Int)
charging = ("It's over", 1)



spec2 : Test.Test
spec2 =
    Test.test "#fst: \n\n    get fst charging\n    --> \"It's over\"" <|
        \() ->
            Expect.equal
                (
                get fst charging
                )
                (
                "It's over"
                )