module VerifyExamples.Accessors.Is0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#is: \n\n    [\"Stuff\", \"things\"]\n        |> is (at 0)\n    --> True" <|
        \() ->
            Expect.equal
                (
                ["Stuff", "things"]
                    |> is (at 0)
                )
                (
                True
                )