module VerifyExamples.Accessors.Is2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#is: \n\n    Nothing\n        |> is try\n    --> False" <|
        \() ->
            Expect.equal
                (
                Nothing
                    |> is try
                )
                (
                False
                )