module VerifyExamples.Accessors.Is3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)







spec3 : Test.Test
spec3 =
    Test.test "#is: \n\n    Just 1234\n        |> is try\n    --> True" <|
        \() ->
            Expect.equal
                (
                Just 1234
                    |> is try
                )
                (
                True
                )