module VerifyExamples.Accessors.Ix0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Lens as L
import Accessors exposing (..)
import Array exposing (Array)



arr : Array { bar : String }
arr = Array.fromList [{ bar = "Stuff" }, { bar =  "Things" }, { bar = "Woot" }]



spec0 : Test.Test
spec0 =
    Test.test "#ix: \n\n    set (ix 9000 << L.bar) \"Whatever\" arr\n    --> arr" <|
        \() ->
            Expect.equal
                (
                set (ix 9000 << L.bar) "Whatever" arr
                )
                (
                arr
                )