module VerifyExamples.Accessors.Ix4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Lens as L
import Accessors exposing (..)
import Array exposing (Array)



arr : Array { bar : String }
arr = Array.fromList [{ bar = "Stuff" }, { bar =  "Things" }, { bar = "Woot" }]



spec4 : Test.Test
spec4 =
    Test.test "#ix: \n\n    get (ix 1) arr\n    --> Just { bar = \"Things\" }" <|
        \() ->
            Expect.equal
                (
                get (ix 1) arr
                )
                (
                Just { bar = "Things" }
                )