module VerifyExamples.Accessors.Key2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Test.Accessors.Record as R
import Accessors exposing (..)
import Dict exposing (Dict)



dict : Dict String {bar : Int}
dict = Dict.fromList [("foo", {bar = 2})]



spec2 : Test.Test
spec2 =
    Test.test "#key: \n\n    get (key \"foo\" << try << R.bar) dict\n    --> Just 2" <|
        \() ->
            Expect.equal
                (
                get (key "foo" << try << R.bar) dict
                )
                (
                Just 2
                )