module VerifyExamples.Accessors.Key3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Test.Accessors.Record as R
import Accessors exposing (..)
import Dict exposing (Dict)



dict : Dict String {bar : Int}
dict = Dict.fromList [("foo", {bar = 2})]



spec3 : Test.Test
spec3 =
    Test.test "#key: \n\n    get (key \"baz\") dict\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                get (key "baz") dict
                )
                (
                Nothing
                )