module VerifyExamples.Accessors.Key4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Lens as L
import Accessors exposing (..)
import Dict exposing (Dict)



dict : Dict String {bar : Int}
dict = Dict.fromList [("foo", {bar = 2})]



spec4 : Test.Test
spec4 =
    Test.test "#key: \n\n    get (key \"foo\") dict\n    --> Just {bar = 2}" <|
        \() ->
            Expect.equal
                (
                get (key "foo") dict
                )
                (
                Just {bar = 2}
                )