module VerifyExamples.Accessors.Ok0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Lens as L
import Accessors exposing (..)



maybeRecord : { foo : Result String { bar : Int }, qux : Result String { bar : Int } }
maybeRecord = { foo = Ok { bar = 2 }
              , qux = Err "Not an Int"
              }



spec0 : Test.Test
spec0 =
    Test.test "#ok: \n\n    over (L.qux << ok << L.bar) ((+) 1) maybeRecord\n    --> { foo = Ok { bar = 2 }, qux = Err \"Not an Int\" }" <|
        \() ->
            Expect.equal
                (
                over (L.qux << ok << L.bar) ((+) 1) maybeRecord
                )
                (
                { foo = Ok { bar = 2 }, qux = Err "Not an Int" }
                )