module VerifyExamples.Accessors.One0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Accessors exposing (..)



charging : (String, Int)
charging = ("It's over", 1)



spec0 : Test.Test
spec0 =
    Test.test "#one: \n\n    over one (\\s -> String.toUpper s ++ \"!!!\") charging\n    --> (\"IT'S OVER!!!\", 1)" <|
        \() ->
            Expect.equal
                (
                over one (\s -> String.toUpper s ++ "!!!") charging
                )
                (
                ("IT'S OVER!!!", 1)
                )