module VerifyExamples.Accessors.One1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Accessors exposing (..)



charging : (String, Int)
charging = ("It's over", 1)



spec1 : Test.Test
spec1 =
    Test.test "#one: \n\n    set one \"It's over\" charging\n    --> (\"It's over\", 1)" <|
        \() ->
            Expect.equal
                (
                set one "It's over" charging
                )
                (
                ("It's over", 1)
                )