module VerifyExamples.Accessors.Snd1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Accessors exposing (..)



meh : (String, Int)
meh = ("It's over", 1)



spec1 : Test.Test
spec1 =
    Test.test "#snd: \n\n    set snd 1125 meh\n    --> (\"It's over\", 1125)" <|
        \() ->
            Expect.equal
                (
                set snd 1125 meh
                )
                (
                ("It's over", 1125)
                )