module VerifyExamples.Accessors.Try0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Lens as L
import Accessors exposing (..)



maybeRecord : { foo : Maybe { bar : Int }, qux : Maybe { bar : Int } }
maybeRecord = { foo = Just { bar = 2 }
              , qux = Nothing
              }



spec0 : Test.Test
spec0 =
    Test.test "#try: \n\n    over (L.qux << try << L.bar) ((+) 1) maybeRecord\n    --> {foo = Just {bar = 2}, qux = Nothing}" <|
        \() ->
            Expect.equal
                (
                over (L.qux << try << L.bar) ((+) 1) maybeRecord
                )
                (
                {foo = Just {bar = 2}, qux = Nothing}
                )