module VerifyExamples.Accessors.Try1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Test.Accessors.Record as R
import Accessors exposing (..)



maybeRecord : { foo : Maybe { bar : Int }, qux : Maybe { bar : Int } }
maybeRecord = { foo = Just { bar = 2 }
              , qux = Nothing
              }



spec1 : Test.Test
spec1 =
    Test.test "#try: \n\n    over (R.foo << try << R.bar) ((+) 1) maybeRecord\n    --> {foo = Just {bar = 3}, qux = Nothing}" <|
        \() ->
            Expect.equal
                (
                over (R.foo << try << R.bar) ((+) 1) maybeRecord
                )
                (
                {foo = Just {bar = 3}, qux = Nothing}
                )