module VerifyExamples.Accessors.Try2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Test.Accessors.Record as R
import Accessors exposing (..)



maybeRecord : { foo : Maybe { bar : Int }, qux : Maybe { bar : Int } }
maybeRecord = { foo = Just { bar = 2 }
              , qux = Nothing
              }



spec2 : Test.Test
spec2 =
    Test.test "#try: \n\n    get (R.qux << try << R.bar) maybeRecord\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                get (R.qux << try << R.bar) maybeRecord
                )
                (
                Nothing
                )