module VerifyExamples.Accessors.Two0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Accessors exposing (..)



meh : (String, Int)
meh = ("It's over", 1)



spec0 : Test.Test
spec0 =
    Test.test "#two: \n\n    meh\n        |> set two 1125\n        |> over one (\\s -> String.toUpper s ++ \"!!!\")\n        |> over two ((*) 8)\n    --> (\"IT'S OVER!!!\", 9000)" <|
        \() ->
            Expect.equal
                (
                meh
                    |> set two 1125
                    |> over one (\s -> String.toUpper s ++ "!!!")
                    |> over two ((*) 8)
                )
                (
                ("IT'S OVER!!!", 9000)
                )